// Genere par scripts/build-blog-meta.mjs — ne pas editer a la main.
// Metadonnees des articles, sans leur corps : importable depuis n'importe
// quelle page sans tirer les 116 fichiers de contenu.

export type BlogMeta = {
  slug: string;
  category: string;
  date: string;
  readingTime: string;
  title: string;
  excerpt: string;
  heroImg: string;
  heroAlt: string;
};

export const BLOG_META: BlogMeta[] = [
  {
    slug: "quand-partir-maldives",
    category: "Conseils",
    date: "Juin 2026",
    readingTime: "8 min",
    title: "Quand partir aux Maldives ? Le guide saison par saison",
    excerpt: "Saison sèche, mousson, meilleurs spots et atolls secrets : tout ce qu'il faut savoir pour choisir le meilleur moment et profiter d'un lagon parfait.",
    heroImg: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=1600&h=900&fit=crop&auto=format",
    heroAlt: "Villas sur pilotis au-dessus d'un lagon turquoise aux Maldives",
  },
  {
    slug: "plus-belles-plages-ocean-indien",
    category: "Inspiration",
    date: "Juin 2026",
    readingTime: "7 min",
    title: "Les 10 plus belles plages de l'océan Indien",
    excerpt: "Sable corallien, lagons turquoise et rochers de granit sculptés : notre sélection des plus belles plages de l'océan Indien, de Maurice aux Maldives.",
    heroImg: "/generated/blog-plus-belles-plages-ocean-indien-hero.jpg",
    heroAlt: "Plage de sable blanc bordée de cocotiers et lagon turquoise dans l'océan Indien",
  },
  {
    slug: "city-break-europe-hors-saison",
    category: "Inspiration",
    date: "Mai 2026",
    readingTime: "6 min",
    title: "City break : 5 villes européennes à découvrir hors saison",
    excerpt: "Moins de foule, des tarifs plus doux et une lumière magique : voici cinq villes d'Europe à savourer hors saison, avec nos repères pour réussir chaque escapade.",
    heroImg: "/generated/blog-city-break-europe-hors-saison-hero.jpg",
    heroAlt: "Ruelle pavée d'une vieille ville européenne baignée par la lumière dorée du matin hors saison",
  },
  {
    slug: "voyage-famille-astuces",
    category: "Conseils",
    date: "Mai 2026",
    readingTime: "7 min",
    title: "Voyage en famille : nos astuces pour des vacances réussies",
    excerpt: "Choisir la bonne destination, préparer les bagages, occuper petits et grands sans stress : nos conseils d'experts pour des vacances en famille inoubliables.",
    heroImg: "/generated/blog-voyage-famille-astuces-hero.jpg",
    heroAlt: "Famille souriante marchant sur une plage ensoleillée pendant les vacances",
  },
  {
    slug: "safari-tanzanie-checklist",
    category: "Pratique",
    date: "Avril 2026",
    readingTime: "8 min",
    title: "Safari en Tanzanie : la check-list avant de partir",
    excerpt: "Saison sèche, grande migration, parcs mythiques, formalités et valise idéale : tout ce qu'il faut préparer pour vivre un safari inoubliable en Tanzanie.",
    heroImg: "/generated/blog-safari-tanzanie-checklist-hero.jpg",
    heroAlt: "Éléphants traversant la savane au coucher du soleil lors d'un safari en Tanzanie",
  },
  {
    slug: "lune-de-miel-destination",
    category: "Inspiration",
    date: "Avril 2026",
    readingTime: "6 min",
    title: "Lune de miel : comment choisir la destination idéale ?",
    excerpt: "Plage paradisiaque, grands espaces ou escapade romantique : tout ce qu'il faut savoir pour choisir la destination de votre voyage de noces selon vos envies à deux.",
    heroImg: "/generated/blog-lune-de-miel-destination-hero.jpg",
    heroAlt: "Couple de jeunes mariés marchant main dans la main sur une plage au coucher du soleil",
  },
  {
    slug: "quand-partir-thailande",
    category: "Conseils",
    date: "janvier 2025",
    readingTime: "6 min",
    title: "Quand partir en Thaïlande ? Climat et saisons",
    excerpt: "Saison sèche, mousson et microclimats : tout ce qu'il faut savoir pour choisir le bon mois et réussir votre voyage en Thaïlande.",
    heroImg: "/generated/blog-quand-partir-thailande-hero.jpg",
    heroAlt: "Plage thaïlandaise avec bateau à longue queue devant des falaises calcaires",
  },
  {
    slug: "quand-partir-bali",
    category: "Conseils",
    date: "février 2025",
    readingTime: "7 min",
    title: "Quand partir à Bali ? Le guide des saisons",
    excerpt: "Saison sèche, saison des pluies et pics d'affluence : tout ce qu'il faut savoir pour choisir le meilleur moment pour découvrir l'île des Dieux.",
    heroImg: "/generated/blog-quand-partir-bali-hero.jpg",
    heroAlt: "Rizières en terrasses verdoyantes et temple hindou à Bali en Indonésie",
  },
  {
    slug: "quand-partir-maroc",
    category: "Conseils",
    date: "mars 2025",
    readingTime: "5 min",
    title: "Quand partir au Maroc ? Climat ville par ville",
    excerpt: "Marrakech, désert, montagnes et côte atlantique : tout ce qu'il faut savoir pour choisir la meilleure période selon votre destination au Maroc.",
    heroImg: "/generated/blog-quand-partir-maroc-hero.jpg",
    heroAlt: "Toits de la médina de Marrakech avec les montagnes de l'Atlas en arrière-plan",
  },
  {
    slug: "quand-partir-grece",
    category: "Conseils",
    date: "avril 2025",
    readingTime: "8 min",
    title: "Quand partir en Grèce ? Météo et meilleures périodes",
    excerpt: "Météo, affluence et budget : tout ce qu'il faut savoir pour choisir le meilleur moment et profiter pleinement des îles grecques et du continent.",
    heroImg: "/generated/blog-quand-partir-grece-hero.jpg",
    heroAlt: "Maisons blanches et dômes bleus de Santorin surplombant la mer Égée",
  },
  {
    slug: "quand-partir-italie",
    category: "Conseils",
    date: "mai 2025",
    readingTime: "6 min",
    title: "Quand partir en Italie ? Saison par saison",
    excerpt: "Villes d'art, lacs, Toscane et côte amalfitaine : tout ce qu'il faut savoir pour choisir la meilleure période selon votre destination en Italie.",
    heroImg: "/generated/blog-quand-partir-italie-hero.jpg",
    heroAlt: "Collines vallonnées de Toscane parsemées de cyprès sous la lumière dorée",
  },
  {
    slug: "quand-partir-espagne",
    category: "Conseils",
    date: "juin 2025",
    readingTime: "7 min",
    title: "Quand partir en Espagne ? Le guide complet",
    excerpt: "Du printemps andalou aux étés des Baléares : tout ce qu'il faut savoir pour choisir le meilleur moment selon la région que vous visez.",
    heroImg: "/generated/blog-quand-partir-espagne-hero.jpg",
    heroAlt: "Architecture colorée de Barcelone sous un ciel d'été lumineux en Espagne",
  },
  {
    slug: "quand-partir-portugal",
    category: "Conseils",
    date: "juillet 2025",
    readingTime: "5 min",
    title: "Quand partir au Portugal ? Climat et conseils",
    excerpt: "De l'Algarve ensoleillé aux Açores verdoyantes : nos repères pour choisir la meilleure période selon la région que vous visez.",
    heroImg: "/generated/blog-quand-partir-portugal-hero.jpg",
    heroAlt: "Tramway jaune et façades d'azulejos dans les rues de Lisbonne",
  },
  {
    slug: "quand-partir-vietnam",
    category: "Conseils",
    date: "août 2025",
    readingTime: "8 min",
    title: "Quand partir au Vietnam ? Nord, centre et sud",
    excerpt: "Le Vietnam s'étire sur plus de 1 600 km et cumule trois climats : voici comment choisir la bonne période selon votre itinéraire.",
    heroImg: "/generated/blog-quand-partir-vietnam-hero.jpg",
    heroAlt: "Jonques traditionnelles naviguant entre les pitons karstiques de la baie d'Halong",
  },
  {
    slug: "quand-partir-japon",
    category: "Conseils",
    date: "septembre 2025",
    readingTime: "6 min",
    title: "Quand partir au Japon ? Saisons et cerisiers",
    excerpt: "Sakura au printemps, érables flamboyants à l'automne, neige immaculée en hiver : le Japon se vit différemment à chaque saison.",
    heroImg: "/generated/blog-quand-partir-japon-hero.jpg",
    heroAlt: "Cerisiers en fleurs devant une pagode avec le mont Fuji en arrière-plan au Japon",
  },
  {
    slug: "quand-partir-new-york",
    category: "Conseils",
    date: "octobre 2025",
    readingTime: "7 min",
    title: "Quand partir à New York ? La meilleure saison",
    excerpt: "Du printemps fleuri à Central Park au New York magique de Noël : nos repères pour choisir le meilleur moment pour visiter la Grosse Pomme.",
    heroImg: "/generated/blog-quand-partir-new-york-hero.jpg",
    heroAlt: "Skyline de Manhattan illuminée au coucher du soleil à New York",
  },
  {
    slug: "quand-partir-islande",
    category: "Conseils",
    date: "novembre 2025",
    readingTime: "5 min",
    title: "Quand partir en Islande ? Été ou hiver, le guide complet",
    excerpt: "Soleil de minuit en été, aurores boréales en hiver : tout ce qu'il faut savoir pour choisir la meilleure période et vivre l'Islande à son apogée.",
    heroImg: "/generated/blog-quand-partir-islande-hero.jpg",
    heroAlt: "Cascade islandaise et aurores boréales vertes dans un ciel nocturne",
  },
  {
    slug: "quand-partir-croatie",
    category: "Conseils",
    date: "décembre 2025",
    readingTime: "8 min",
    title: "Quand partir en Croatie ? Météo, saisons et affluence",
    excerpt: "Soleil dalmate, eaux limpides, villes médiévales et parcs nationaux : tout pour choisir la meilleure période et profiter de la Croatie sans la foule.",
    heroImg: "/generated/blog-quand-partir-croatie-hero.jpg",
    heroAlt: "Vieille ville de Dubrovnik et toits rouges au bord de l'Adriatique",
  },
  {
    slug: "quand-partir-egypte",
    category: "Conseils",
    date: "janvier 2026",
    readingTime: "6 min",
    title: "Quand partir en Égypte ? Climat, croisières et saisons",
    excerpt: "Pyramides, croisière sur le Nil et plongée en mer Rouge : tout ce qu'il faut savoir pour choisir le bon moment et éviter la chaleur écrasante.",
    heroImg: "/generated/blog-quand-partir-egypte-hero.jpg",
    heroAlt: "Pyramides de Gizeh et Sphinx au coucher du soleil en Égypte",
  },
  {
    slug: "quand-partir-sri-lanka",
    category: "Conseils",
    date: "février 2026",
    readingTime: "7 min",
    title: "Quand partir au Sri Lanka ? Comprendre les deux moussons",
    excerpt: "Deux moussons opposées, plantations de thé, plages de rêve et safaris : tout pour choisir la bonne période selon la région du Sri Lanka.",
    heroImg: "/generated/blog-quand-partir-sri-lanka-hero.jpg",
    heroAlt: "Collines verdoyantes couvertes de plantations de thé au Sri Lanka",
  },
  {
    slug: "quand-partir-mexique",
    category: "Conseils",
    date: "mars 2026",
    readingTime: "5 min",
    title: "Quand partir au Mexique ? Saison sèche et saison des pluies",
    excerpt: "Plages turquoise, cités mayas et culture flamboyante : tout pour choisir la meilleure période entre saison sèche et saison des pluies au Mexique.",
    heroImg: "/generated/blog-quand-partir-mexique-hero.jpg",
    heroAlt: "Ruines mayas de Tulum dominant une plage turquoise au Mexique",
  },
  {
    slug: "quand-partir-cap-vert",
    category: "Conseils",
    date: "avril 2026",
    readingTime: "8 min",
    title: "Quand partir au Cap-Vert ? Soleil toute l'année",
    excerpt: "Climat doux, alizés, baignade et randonnée : tout ce qu'il faut savoir pour choisir le meilleur moment et la bonne île de l'archipel cap-verdien.",
    heroImg: "/generated/blog-quand-partir-cap-vert-hero.jpg",
    heroAlt: "Plage de sable blanc et dunes volcaniques bordées d'un océan turquoise au Cap-Vert",
  },
  {
    slug: "quand-partir-republique-dominicaine",
    category: "Conseils",
    date: "mai 2026",
    readingTime: "6 min",
    title: "Quand partir en République dominicaine ?",
    excerpt: "Saison sèche, pluies, cyclones et baleines à bosse : tout ce qu'il faut savoir pour choisir le meilleur moment et la bonne région des Caraïbes.",
    heroImg: "/generated/blog-quand-partir-republique-dominicaine-hero.jpg",
    heroAlt: "Plage de cocotiers et mer turquoise sous un ciel bleu en République dominicaine",
  },
  {
    slug: "quand-partir-cuba",
    category: "Conseils",
    date: "juin 2026",
    readingTime: "7 min",
    title: "Quand partir à Cuba ? Climat et meilleurs mois",
    excerpt: "Saison sèche, pluies, cyclones et festivals : tout ce qu'il faut savoir pour choisir le meilleur moment et profiter pleinement de la perle des Caraïbes.",
    heroImg: "/generated/blog-quand-partir-cuba-hero.jpg",
    heroAlt: "Voitures américaines vintage devant des façades colorées de La Havane à Cuba",
  },
  {
    slug: "quand-partir-tanzanie",
    category: "Conseils",
    date: "janvier 2025",
    readingTime: "5 min",
    title: "Quand partir en Tanzanie ? Safari et migration",
    excerpt: "Saison sèche, grande migration, ascension du Kilimandjaro et plages de Zanzibar : tout pour choisir le meilleur moment de votre voyage en Tanzanie.",
    heroImg: "/generated/blog-quand-partir-tanzanie-hero.jpg",
    heroAlt: "Éléphants traversant la savane du Serengeti au coucher du soleil en Tanzanie",
  },
  {
    slug: "quand-partir-afrique-du-sud",
    category: "Conseils",
    date: "février 2025",
    readingTime: "8 min",
    title: "Quand partir en Afrique du Sud ? Le guide",
    excerpt: "Safari au Kruger, baleines de Hermanus, Le Cap et Route des Jardins : tout pour choisir le meilleur moment selon les régions d'Afrique du Sud.",
    heroImg: "/generated/blog-quand-partir-afrique-du-sud-hero.jpg",
    heroAlt: "La Montagne de la Table dominant Le Cap sous un ciel dégagé en Afrique du Sud",
  },
  {
    slug: "quand-partir-la-reunion",
    category: "Conseils",
    date: "mars 2025",
    readingTime: "6 min",
    title: "Quand partir à La Réunion ? Saisons et cyclones",
    excerpt: "Saison sèche, saison des pluies, cyclones et microclimats : tout ce qu'il faut savoir pour choisir le meilleur moment et profiter de l'île intense.",
    heroImg: "/generated/blog-quand-partir-la-reunion-hero.jpg",
    heroAlt: "Volcan et cirque verdoyant de La Réunion sous un ciel dégagé",
  },
  {
    slug: "quand-partir-ile-maurice",
    category: "Conseils",
    date: "avril 2025",
    readingTime: "7 min",
    title: "Quand partir à l'île Maurice ? La météo idéale",
    excerpt: "Saison sèche, été austral, microclimats et meilleures côtes : tout ce qu'il faut savoir pour choisir le bon moment et profiter du lagon mauricien.",
    heroImg: "/generated/blog-quand-partir-ile-maurice-hero.jpg",
    heroAlt: "Lagon turquoise et villas sur pilotis à l'île Maurice",
  },
  {
    slug: "quand-partir-canada",
    category: "Conseils",
    date: "mai 2025",
    readingTime: "5 min",
    title: "Quand partir au Canada ? Été indien et hiver",
    excerpt: "Été doux, été indien flamboyant, hiver féerique et aurores boréales : tout ce qu'il faut savoir pour choisir le meilleur moment pour partir au Canada.",
    heroImg: "/generated/blog-quand-partir-canada-hero.jpg",
    heroAlt: "Lac turquoise des Rocheuses canadiennes aux couleurs d'automne",
  },
  {
    slug: "quand-partir-jordanie",
    category: "Conseils",
    date: "juin 2025",
    readingTime: "8 min",
    title: "Quand partir en Jordanie ? Climat et désert",
    excerpt: "Printemps fleuri, automne doux, chaleur estivale et nuits du désert : tout ce qu'il faut savoir pour choisir le meilleur moment pour partir en Jordanie.",
    heroImg: "/generated/blog-quand-partir-jordanie-hero.jpg",
    heroAlt: "Façade du Trésor de Petra en pierre rose au lever du soleil",
  },
  {
    slug: "ou-partir-en-janvier",
    category: "Inspiration",
    date: "juillet 2025",
    readingTime: "6 min",
    title: "Où partir en janvier ? Soleil et bons plans",
    excerpt: "Plages tropicales, sports d'hiver ou escapades culturelles à prix doux : nos meilleures idées de destinations pour bien commencer l'année en janvier.",
    heroImg: "/generated/blog-ou-partir-en-janvier-hero.jpg",
    heroAlt: "Plage tropicale au sable blanc et cocotiers sous le soleil d'hiver",
  },
  {
    slug: "ou-partir-en-fevrier",
    category: "Inspiration",
    date: "août 2025",
    readingTime: "7 min",
    title: "Où partir en février ? Soleil, neige et carnaval",
    excerpt: "Entre plages tropicales, montagnes enneigées et carnavals hauts en couleur, février offre un éventail de destinations pour tous les envies de voyage.",
    heroImg: "/generated/blog-ou-partir-en-fevrier-hero.jpg",
    heroAlt: "Plage tropicale ensoleillée et sommet enneigé au loin en février",
  },
  {
    slug: "ou-partir-en-mars",
    category: "Inspiration",
    date: "septembre 2025",
    readingTime: "5 min",
    title: "Où partir en mars ? Nos idées de destinations",
    excerpt: "Le printemps s'éveille, les déserts fleurissent et les plages se réchauffent : mars est un mois charnière idéal pour voyager loin de la foule.",
    heroImg: "/generated/blog-ou-partir-en-mars-hero.jpg",
    heroAlt: "Paysage de printemps avec cerisiers en fleurs au mois de mars",
  },
  {
    slug: "ou-partir-en-avril",
    category: "Inspiration",
    date: "octobre 2025",
    readingTime: "8 min",
    title: "Où partir en avril ? Le top des destinations",
    excerpt: "Nature en fleurs, météo douce et affluence modérée : avril est l'un des plus beaux mois pour voyager, de l'Europe au Japon en passant par les tropiques.",
    heroImg: "/generated/blog-ou-partir-en-avril-hero.jpg",
    heroAlt: "Paysage de printemps verdoyant et ville historique en avril",
  },
  {
    slug: "ou-partir-en-mai",
    category: "Inspiration",
    date: "novembre 2025",
    readingTime: "6 min",
    title: "Où partir en mai ? Climat doux et nature",
    excerpt: "Méditerranée fleurie, plages encore tranquilles et nature généreuse : mai est un mois doux et lumineux, parfait pour voyager avant l'affluence estivale.",
    heroImg: "/generated/blog-ou-partir-en-mai-hero.jpg",
    heroAlt: "Côte méditerranéenne fleurie sous le soleil au mois de mai",
  },
  {
    slug: "ou-partir-en-juin",
    category: "Inspiration",
    date: "décembre 2025",
    readingTime: "7 min",
    title: "Où partir en juin ? Avant la haute saison",
    excerpt: "Soleil généreux, mer qui se réchauffe et affluence encore modérée : juin est le mois idéal pour profiter de l'été avant la cohue des vacances.",
    heroImg: "/generated/blog-ou-partir-en-juin-hero.jpg",
    heroAlt: "Littoral européen aux eaux turquoise sous le soleil de juin",
  },
  {
    slug: "ou-partir-en-juillet",
    category: "Inspiration",
    date: "janvier 2026",
    readingTime: "5 min",
    title: "Où partir en juillet ? Nos meilleures idées de destinations",
    excerpt: "Soleil garanti en Méditerranée, lagons d'Indonésie ou grands parcs d'Amérique : nos idées pour un mois de juillet réussi, au soleil comme au frais.",
    heroImg: "/generated/blog-ou-partir-en-juillet-hero.jpg",
    heroAlt: "Lagon turquoise bordé de palmiers sous un ciel d'été éclatant en juillet",
  },
  {
    slug: "ou-partir-en-aout",
    category: "Inspiration",
    date: "février 2026",
    readingTime: "8 min",
    title: "Où partir en août ? Mer, montagne et ailleurs",
    excerpt: "Plages d'Europe, lacs alpins, grands espaces nordiques ou hiver austral : nos destinations pour un mois d'août inoubliable, au soleil ou au frais.",
    heroImg: "/generated/blog-ou-partir-en-aout-hero.jpg",
    heroAlt: "Lac alpin turquoise et littoral ensoleillé évoquant les vacances d'août",
  },
  {
    slug: "ou-partir-en-septembre",
    category: "Inspiration",
    date: "mars 2026",
    readingTime: "6 min",
    title: "Où partir en septembre ? Profiter de l'arrière-saison",
    excerpt: "Méditerranée apaisée, vendanges, mer encore chaude et moins de monde : nos idées pour savourer l'arrière-saison de septembre, ici comme à l'autre bout du monde.",
    heroImg: "/generated/blog-ou-partir-en-septembre-hero.jpg",
    heroAlt: "Village côtier baigné par la lumière dorée de l'arrière-saison en septembre",
  },
  {
    slug: "ou-partir-en-octobre",
    category: "Inspiration",
    date: "avril 2026",
    readingTime: "7 min",
    title: "Où partir en octobre ? Le soleil d'automne",
    excerpt: "Douceur méditerranéenne, feuillages d'automne, déserts et tropiques au beau fixe : nos idées pour un mois d'octobre ensoleillé et dépaysant.",
    heroImg: "/generated/blog-ou-partir-en-octobre-hero.jpg",
    heroAlt: "Forêt aux couleurs d'automne et littoral ensoleillé en octobre",
  },
  {
    slug: "ou-partir-en-novembre",
    category: "Inspiration",
    date: "mai 2026",
    readingTime: "5 min",
    title: "Où partir en novembre ? Échapper à la grisaille",
    excerpt: "Lagons tropicaux, déserts ensoleillés, océan Indien et grands voyages : nos idées pour fuir la grisaille de novembre et retrouver le soleil.",
    heroImg: "/generated/blog-ou-partir-en-novembre-hero.jpg",
    heroAlt: "Plage tropicale ensoleillée bordée de palmiers pour échapper à la grisaille de novembre",
  },
  {
    slug: "ou-partir-en-decembre",
    category: "Inspiration",
    date: "juin 2026",
    readingTime: "8 min",
    title: "Où partir en décembre ? Fêtes et soleil garantis",
    excerpt: "Plages tropicales, marchés de Noël enchantés ou grand froid féérique : nos destinations préférées pour réussir vos vacances de décembre.",
    heroImg: "/generated/blog-ou-partir-en-decembre-hero.jpg",
    heroAlt: "Plage tropicale ensoleillée et marché de Noël illuminé en décembre",
  },
  {
    slug: "visiter-rome-3-jours",
    category: "Itinéraire",
    date: "janvier 2025",
    readingTime: "6 min",
    title: "Visiter Rome en 3 jours : l'itinéraire idéal",
    excerpt: "Antiquité, Vatican et dolce vita : notre programme jour par jour pour découvrir l'essentiel de Rome en un long week-end de 3 jours.",
    heroImg: "/generated/blog-visiter-rome-3-jours-hero.jpg",
    heroAlt: "Le Colisée de Rome illuminé à l'heure dorée du coucher de soleil",
  },
  {
    slug: "visiter-lisbonne-week-end",
    category: "Itinéraire",
    date: "février 2025",
    readingTime: "7 min",
    title: "Visiter Lisbonne en un week-end : notre itinéraire",
    excerpt: "Collines, azulejos, tram jaune et pastéis de nata : notre programme pour découvrir l'essentiel de Lisbonne le temps d'un week-end ensoleillé.",
    heroImg: "/generated/blog-visiter-lisbonne-week-end-hero.jpg",
    heroAlt: "Tramway jaune sur une rue en pente de Lisbonne avec toits orange",
  },
  {
    slug: "que-faire-a-marrakech",
    category: "Itinéraire",
    date: "mars 2025",
    readingTime: "5 min",
    title: "Que faire à Marrakech ? Les incontournables",
    excerpt: "Souks animés, palais raffinés, jardins luxuriants et riads cachés : notre sélection des lieux à ne pas manquer pour découvrir la ville rouge.",
    heroImg: "/generated/blog-que-faire-a-marrakech-hero.jpg",
    heroAlt: "Souk coloré de Marrakech avec épices, lanternes et étals animés",
  },
  {
    slug: "que-faire-a-bali",
    category: "Itinéraire",
    date: "avril 2025",
    readingTime: "8 min",
    title: "Que faire à Bali ? Nos coups de cœur",
    excerpt: "Temples sacrés, rizières en terrasses, plages de rêve et cascades cachées : notre sélection des plus belles expériences à vivre sur l'île des dieux.",
    heroImg: "/generated/blog-que-faire-a-bali-hero.jpg",
    heroAlt: "Portes d'un temple balinais ouvertes sur la jungle et une cascade",
  },
  {
    slug: "road-trip-ecosse",
    category: "Itinéraire",
    date: "mai 2025",
    readingTime: "6 min",
    title: "Road trip en Écosse : itinéraire et conseils",
    excerpt: "Châteaux hantés, lochs mystérieux et routes désertes des Highlands : voici notre itinéraire jour par jour pour réussir votre road trip en Écosse.",
    heroImg: "/generated/blog-road-trip-ecosse-hero.jpg",
    heroAlt: "Château écossais dominant un loch brumeux au cœur des Highlands",
  },
  {
    slug: "road-trip-islande",
    category: "Itinéraire",
    date: "juin 2025",
    readingTime: "7 min",
    title: "Road trip en Islande : la route circulaire",
    excerpt: "La Ring Road fait le tour de l'Islande en reliant ses plus beaux sites : cascades, glaciers et plages noires. Voici notre itinéraire jour par jour.",
    heroImg: "/generated/blog-road-trip-islande-hero.jpg",
    heroAlt: "Cascade puissante au cœur d'un paysage volcanique islandais",
  },
  {
    slug: "road-trip-ouest-americain",
    category: "Itinéraire",
    date: "juillet 2025",
    readingTime: "5 min",
    title: "Road trip dans l'Ouest américain",
    excerpt: "Canyons vertigineux, déserts rouges et parcs nationaux mythiques : voici notre itinéraire jour par jour pour un road trip inoubliable dans l'Ouest américain.",
    heroImg: "/generated/blog-road-trip-ouest-americain-hero.jpg",
    heroAlt: "Route déserte traversant les paysages rouges de l'Ouest américain",
  },
  {
    slug: "visiter-new-york-premiere-fois",
    category: "Itinéraire",
    date: "août 2025",
    readingTime: "8 min",
    title: "Visiter New York pour la première fois",
    excerpt: "Gratte-ciel, quartiers mythiques et musées de légende : voici notre itinéraire jour par jour pour découvrir l'essentiel de New York lors d'un premier séjour.",
    heroImg: "/generated/blog-visiter-new-york-premiere-fois-hero.jpg",
    heroAlt: "Taxis jaunes et gratte-ciel illuminés de Times Square à New York",
  },
  {
    slug: "itineraire-japon-2-semaines",
    category: "Itinéraire",
    date: "septembre 2025",
    readingTime: "6 min",
    title: "Le Japon en 2 semaines : itinéraire parfait",
    excerpt: "Tokyo trépidante, Kyoto millénaire et mont Fuji majestueux : voici notre itinéraire jour par jour pour découvrir l'essentiel du Japon en deux semaines.",
    heroImg: "/generated/blog-itineraire-japon-2-semaines-hero.jpg",
    heroAlt: "Pagode japonaise devant le mont Fuji aux couleurs de l'automne",
  },
  {
    slug: "itineraire-vietnam-3-semaines",
    category: "Itinéraire",
    date: "octobre 2025",
    readingTime: "7 min",
    title: "Le Vietnam en 3 semaines, du nord au sud",
    excerpt: "Hanoï, la baie d'Halong, les rizières de Sapa, Hué, Hoi An et le delta du Mékong : notre itinéraire complet pour traverser le Vietnam en trois semaines.",
    heroImg: "/generated/blog-itineraire-vietnam-3-semaines-hero.jpg",
    heroAlt: "Rizières en terrasses verdoyantes de Sapa au nord du Vietnam sous la brume",
  },
  {
    slug: "que-faire-a-dubai",
    category: "Itinéraire",
    date: "novembre 2025",
    readingTime: "5 min",
    title: "Que faire à Dubaï ? Les incontournables",
    excerpt: "Gratte-ciel vertigineux, désert doré, souks parfumés et plages de rêve : notre guide des incontournables de Dubaï avec un programme jour par jour.",
    heroImg: "/generated/blog-que-faire-a-dubai-hero.jpg",
    heroAlt: "Skyline de Dubaï dominée par le Burj Khalifa au coucher du soleil",
  },
  {
    slug: "visiter-barcelone-3-jours",
    category: "Itinéraire",
    date: "décembre 2025",
    readingTime: "8 min",
    title: "Visiter Barcelone en 3 jours : l'itinéraire idéal",
    excerpt: "Sagrada Familia, Park Güell, quartier gothique, Ramblas et tapas : notre itinéraire détaillé pour découvrir le meilleur de Barcelone en trois jours.",
    heroImg: "/generated/blog-visiter-barcelone-3-jours-hero.jpg",
    heroAlt: "Façade de la Sagrada Familia de Gaudí se découpant dans le ciel de Barcelone",
  },
  {
    slug: "que-voir-au-perou",
    category: "Itinéraire",
    date: "janvier 2026",
    readingTime: "6 min",
    title: "Que voir au Pérou ? L'itinéraire essentiel",
    excerpt: "Du Machu Picchu au lac Titicaca en passant par Cusco, la vallée sacrée et le canyon de Colca : notre itinéraire essentiel pour découvrir le Pérou.",
    heroImg: "/generated/blog-que-voir-au-perou-hero.jpg",
    heroAlt: "Citadelle inca du Machu Picchu sous la brume au cœur des Andes péruviennes",
  },
  {
    slug: "itineraire-croatie-1-semaine",
    category: "Itinéraire",
    date: "février 2026",
    readingTime: "7 min",
    title: "La Croatie en une semaine : l'itinéraire idéal",
    excerpt: "Dubrovnik, Split, l'île de Hvar et les chutes de Krka : notre itinéraire d'une semaine pour découvrir la côte dalmate et les plus belles îles croates.",
    heroImg: "/generated/blog-itineraire-croatie-1-semaine-hero.jpg",
    heroAlt: "Toits orangés et remparts de la vieille ville de Dubrovnik au bord de l'Adriatique",
  },
  {
    slug: "itineraire-sri-lanka-2-semaines",
    category: "Itinéraire",
    date: "mars 2026",
    readingTime: "5 min",
    title: "Le Sri Lanka en 2 semaines : l'itinéraire idéal",
    excerpt: "Temples, cités antiques, plantations de thé, safaris et plages dorées : notre itinéraire jour par jour pour traverser le Sri Lanka en deux semaines.",
    heroImg: "/generated/blog-itineraire-sri-lanka-2-semaines-hero.jpg",
    heroAlt: "Train bleu traversant les plantations de thé des hauts plateaux du Sri Lanka",
  },
  {
    slug: "autotour-namibie",
    category: "Itinéraire",
    date: "avril 2026",
    readingTime: "8 min",
    title: "Autotour en Namibie : itinéraire et conseils",
    excerpt: "Dunes rouges, canyons vertigineux, côte des Squelettes et safari à Etosha : notre itinéraire et nos conseils pour un road trip inoubliable en Namibie.",
    heroImg: "/generated/blog-autotour-namibie-hero.jpg",
    heroAlt: "Dunes rouges et arbres morts de Deadvlei dans le désert du Namib",
  },
  {
    slug: "itineraire-thailande-2-semaines",
    category: "Itinéraire",
    date: "mai 2026",
    readingTime: "6 min",
    title: "La Thaïlande en 2 semaines : l'itinéraire idéal",
    excerpt: "Temples de Bangkok, jungle de Chiang Mai et plages paradisiaques du sud : notre itinéraire jour par jour pour découvrir la Thaïlande en deux semaines.",
    heroImg: "/generated/blog-itineraire-thailande-2-semaines-hero.jpg",
    heroAlt: "Bateau à longue queue sur une eau turquoise entre des falaises calcaires en Thaïlande",
  },
  {
    slug: "que-faire-aux-acores",
    category: "Itinéraire",
    date: "juin 2026",
    readingTime: "7 min",
    title: "Que faire aux Açores ? Le guide de l'archipel vert",
    excerpt: "Lacs de cratère, sources chaudes, observation des baleines et randonnées volcaniques : tout ce qu'il faut faire et voir aux Açores, le joyau vert de l'Atlantique.",
    heroImg: "/generated/blog-que-faire-aux-acores-hero.jpg",
    heroAlt: "Lacs jumeaux de Sete Cidades dans un cratère verdoyant aux Açores",
  },
  {
    slug: "bali-ou-thailande",
    category: "Comparatif",
    date: "janvier 2025",
    readingTime: "5 min",
    title: "Bali ou Thaïlande : que choisir pour votre voyage ?",
    excerpt: "Plages, temples, budget et ambiance : notre comparatif équilibré pour trancher entre Bali et la Thaïlande selon vos envies et votre profil de voyageur.",
    heroImg: "/generated/blog-bali-ou-thailande-hero.jpg",
    heroAlt: "Plage tropicale et temple asiatique illustrant le choix entre Bali et la Thaïlande",
  },
  {
    slug: "maldives-ou-seychelles",
    category: "Comparatif",
    date: "février 2025",
    readingTime: "8 min",
    title: "Maldives ou Seychelles : comparatif",
    excerpt: "Lagons turquoise contre plages de granit : on compare budget, ambiance, plongée et climat pour vous aider à choisir entre Maldives et Seychelles.",
    heroImg: "/generated/blog-maldives-ou-seychelles-hero.jpg",
    heroAlt: "Lagon turquoise des Maldives et plage de granit des Seychelles côte à côte",
  },
  {
    slug: "crete-ou-santorin",
    category: "Comparatif",
    date: "mars 2025",
    readingTime: "6 min",
    title: "Crète ou Santorin : laquelle choisir ?",
    excerpt: "Grande île aux mille visages ou carte postale des Cyclades : on compare budget, ambiance, plages et durée idéale entre la Crète et Santorin.",
    heroImg: "/generated/blog-crete-ou-santorin-hero.jpg",
    heroAlt: "Village blanc aux dômes bleus surplombant la mer Égée en Grèce",
  },
  {
    slug: "maroc-ou-tunisie",
    category: "Comparatif",
    date: "avril 2025",
    readingTime: "7 min",
    title: "Maroc ou Tunisie : quelle destination ?",
    excerpt: "Médinas envoûtantes, dunes du Sahara et bord de mer : on compare budget, ambiance, culture et plages entre le Maroc et la Tunisie.",
    heroImg: "/generated/blog-maroc-ou-tunisie-hero.jpg",
    heroAlt: "Médina d'Afrique du Nord et dunes de désert sous un ciel doré",
  },
  {
    slug: "vietnam-ou-cambodge",
    category: "Comparatif",
    date: "mai 2025",
    readingTime: "5 min",
    title: "Vietnam ou Cambodge : que préférer ?",
    excerpt: "Rizières et baies spectaculaires contre temples d'Angkor : on compare paysages, budget, durée et ambiance entre le Vietnam et le Cambodge.",
    heroImg: "/generated/blog-vietnam-ou-cambodge-hero.jpg",
    heroAlt: "Temple khmer et rizières en terrasses d'Asie du Sud-Est",
  },
  {
    slug: "cuba-ou-republique-dominicaine",
    category: "Comparatif",
    date: "juin 2025",
    readingTime: "8 min",
    title: "Cuba ou République dominicaine ?",
    excerpt: "Charme intemporel et culture vibrante contre plages de carte postale et tout compris : on compare Cuba et la République dominicaine.",
    heroImg: "/generated/blog-cuba-ou-republique-dominicaine-hero.jpg",
    heroAlt: "Plage de palmiers turquoise des Caraïbes au coucher du soleil",
  },
  {
    slug: "islande-ou-norvege",
    category: "Comparatif",
    date: "juillet 2025",
    readingTime: "6 min",
    title: "Islande ou Norvège : quel voyage nature choisir ?",
    excerpt: "Terres de feu contre royaume des fjords : paysages, activités, budget et saisons, voici comment trancher entre l'Islande et la Norvège.",
    heroImg: "/generated/blog-islande-ou-norvege-hero.jpg",
    heroAlt: "Fjord nordique avec cascade et montagnes spectaculaires",
  },
  {
    slug: "costa-rica-ou-panama",
    category: "Comparatif",
    date: "août 2025",
    readingTime: "7 min",
    title: "Costa Rica ou Panama : quel pays d'Amérique centrale choisir ?",
    excerpt: "Deux paradis de biodiversité face à face : nature, plages, budget et ambiance, voici comment départager le Costa Rica et le Panama.",
    heroImg: "/generated/blog-costa-rica-ou-panama-hero.jpg",
    heroAlt: "Jungle tropicale luxuriante et plage des Caraïbes",
  },
  {
    slug: "plus-belles-iles-du-monde",
    category: "Inspiration",
    date: "septembre 2025",
    readingTime: "5 min",
    title: "Les plus belles îles du monde : notre sélection de rêve",
    excerpt: "Lagons turquoise, sable blanc et nature préservée : tour d'horizon des plus belles îles de la planète pour inspirer votre prochaine évasion.",
    heroImg: "/generated/blog-plus-belles-iles-du-monde-hero.jpg",
    heroAlt: "Île tropicale vue du ciel avec lagon turquoise et récif",
  },
  {
    slug: "plus-beaux-villages-de-france",
    category: "Inspiration",
    date: "octobre 2025",
    readingTime: "8 min",
    title: "Les plus beaux villages de France : notre sélection",
    excerpt: "Ruelles pavées, maisons de pierre et panoramas à couper le souffle : escapade au cœur des plus beaux villages de France.",
    heroImg: "/generated/blog-plus-beaux-villages-de-france-hero.jpg",
    heroAlt: "Village médiéval perché en pierre dorée au coucher du soleil",
  },
  {
    slug: "plus-belles-plages-d-europe",
    category: "Inspiration",
    date: "novembre 2025",
    readingTime: "6 min",
    title: "Les plus belles plages d'Europe : notre sélection",
    excerpt: "Criques cachées, eaux turquoise et falaises spectaculaires : tour d'horizon des plus belles plages d'Europe pour rêver à vos prochaines vacances.",
    heroImg: "/generated/blog-plus-belles-plages-d-europe-hero.jpg",
    heroAlt: "Crique européenne aux eaux turquoise entourée de falaises",
  },
  {
    slug: "plus-beaux-deserts-du-monde",
    category: "Inspiration",
    date: "décembre 2025",
    readingTime: "7 min",
    title: "Les plus beaux déserts du monde",
    excerpt: "Des dunes du Sahara aux salars d'Atacama : notre sélection des déserts les plus spectaculaires de la planète et nos conseils pour les découvrir.",
    heroImg: "/generated/blog-plus-beaux-deserts-du-monde-hero.jpg",
    heroAlt: "Vastes dunes de sable doré ondulant sous une lumière de fin de journée",
  },
  {
    slug: "meilleures-destinations-plongee",
    category: "Inspiration",
    date: "janvier 2026",
    readingTime: "5 min",
    title: "Les meilleures destinations plongée du monde",
    excerpt: "De la Grande Barrière de corail aux Maldives : notre sélection des plus beaux spots de plongée de la planète et nos conseils pour les explorer.",
    heroImg: "/generated/blog-meilleures-destinations-plongee-hero.jpg",
    heroAlt: "Plongeur évoluant au-dessus d'un récif corallien coloré peuplé de poissons tropicaux",
  },
  {
    slug: "plus-beaux-road-trips-du-monde",
    category: "Inspiration",
    date: "février 2026",
    readingTime: "8 min",
    title: "Les plus beaux road trips du monde",
    excerpt: "De la Route 66 à la Garden Route : notre sélection des plus belles routes de la planète et nos conseils pour vivre le road trip de vos rêves.",
    heroImg: "/generated/blog-plus-beaux-road-trips-du-monde-hero.jpg",
    heroAlt: "Route sinueuse longeant une côte spectaculaire entre océan et montagnes",
  },
  {
    slug: "ou-voir-aurores-boreales",
    category: "Inspiration",
    date: "mars 2026",
    readingTime: "6 min",
    title: "Où voir les aurores boréales ?",
    excerpt: "Laponie, Islande, Norvège ou Canada : notre sélection des meilleurs endroits pour observer les aurores boréales et nos conseils pour ne pas les manquer.",
    heroImg: "/generated/blog-ou-voir-aurores-boreales-hero.jpg",
    heroAlt: "Aurore boréale verte ondulant dans un ciel nocturne au-dessus d'un paysage enneigé",
  },
  {
    slug: "plus-belles-iles-grecques",
    category: "Inspiration",
    date: "avril 2026",
    readingTime: "7 min",
    title: "Les plus belles îles grecques",
    excerpt: "Des Cyclades au Dodécanèse : notre sélection des plus belles îles grecques et nos conseils pour choisir celle qui vous ressemble.",
    heroImg: "/generated/blog-plus-belles-iles-grecques-hero.jpg",
    heroAlt: "Maisons blanches aux dômes bleus dominant la mer Égée sur une île grecque",
  },
  {
    slug: "meilleures-destinations-safari",
    category: "Inspiration",
    date: "mai 2026",
    readingTime: "5 min",
    title: "Les meilleures destinations safari",
    excerpt: "Du Serengeti au delta de l'Okavango, notre sélection des plus beaux territoires d'Afrique pour vivre un safari inoubliable.",
    heroImg: "/generated/blog-meilleures-destinations-safari-hero.jpg",
    heroAlt: "Éléphants traversant la savane africaine au coucher du soleil sous un acacia",
  },
  {
    slug: "plus-beaux-sites-unesco",
    category: "Inspiration",
    date: "juin 2026",
    readingTime: "8 min",
    title: "Les plus beaux sites classés UNESCO",
    excerpt: "Merveilles naturelles et chefs-d'œuvre de l'humanité : notre sélection des plus beaux sites du patrimoine mondial à voir au moins une fois.",
    heroImg: "/generated/blog-plus-beaux-sites-unesco-hero.jpg",
    heroAlt: "Monument emblématique inscrit au patrimoine mondial de l'UNESCO au lever du soleil",
  },
  {
    slug: "iles-paradisiaques-pas-cher",
    category: "Inspiration",
    date: "janvier 2025",
    readingTime: "6 min",
    title: "Îles paradisiaques pas chères",
    excerpt: "Sable blanc, lagons turquoise et budget maîtrisé : notre sélection des plus belles îles paradisiaques accessibles sans se ruiner.",
    heroImg: "/generated/blog-iles-paradisiaques-pas-cher-hero.jpg",
    heroAlt: "Plage de sable blanc bordée de cocotiers et lagon turquoise sur une île tropicale",
  },
  {
    slug: "plus-belles-cascades-du-monde",
    category: "Inspiration",
    date: "février 2025",
    readingTime: "7 min",
    title: "Les plus belles cascades du monde",
    excerpt: "Des chutes d'Iguazú aux cataractes Victoria, notre sélection des plus spectaculaires cascades de la planète et nos conseils pour les admirer.",
    heroImg: "/generated/blog-plus-belles-cascades-du-monde-hero.jpg",
    heroAlt: "Immense cascade tropicale plongeant dans un bassin entouré de jungle luxuriante",
  },
  {
    slug: "voyage-solo-femme-destinations",
    category: "Inspiration",
    date: "mars 2025",
    readingTime: "5 min",
    title: "Voyage solo au féminin : où partir ?",
    excerpt: "Destinations sûres, accueillantes et inspirantes : notre sélection pour partir seule en toute sérénité et vivre une aventure en solo réussie.",
    heroImg: "/generated/blog-voyage-solo-femme-destinations-hero.jpg",
    heroAlt: "Voyageuse seule contemplant un paysage panoramique depuis un point de vue",
  },
  {
    slug: "partir-en-amoureux-week-end",
    category: "Inspiration",
    date: "avril 2025",
    readingTime: "8 min",
    title: "Partir en amoureux : nos plus belles idées de week-ends",
    excerpt: "Capitales romantiques, retraites cosy ou escapades exotiques : nos meilleures idées pour offrir à votre couple une parenthèse inoubliable le temps d'un week-end.",
    heroImg: "/generated/blog-partir-en-amoureux-week-end-hero.jpg",
    heroAlt: "Couple enlacé admirant le coucher de soleil sur une ville romantique",
  },
  {
    slug: "destinations-voyage-aventure",
    category: "Inspiration",
    date: "mai 2025",
    readingTime: "6 min",
    title: "Voyage aventure : les meilleures destinations pour se dépasser",
    excerpt: "Trek en altitude, déserts immenses, jungles et fjords : nos destinations coup de cœur et nos conseils pour vivre l'aventure à votre rythme.",
    heroImg: "/generated/blog-destinations-voyage-aventure-hero.jpg",
    heroAlt: "Randonneur face à des montagnes spectaculaires lors d'un trek d'aventure",
  },
  {
    slug: "voyage-gastronomique-destinations",
    category: "Inspiration",
    date: "juin 2025",
    readingTime: "7 min",
    title: "Voyage gastronomique : nos destinations pour se régaler",
    excerpt: "Pasta italiennes, sushis japonais, street food thaïe ou tajines marocains : nos destinations gourmandes et nos conseils pour un voyage qui se savoure.",
    heroImg: "/generated/blog-voyage-gastronomique-destinations-hero.jpg",
    heroAlt: "Étal coloré d'un marché gourmand avec plats et produits frais locaux",
  },
  {
    slug: "vacances-au-ski-hors-alpes",
    category: "Inspiration",
    date: "juillet 2025",
    readingTime: "5 min",
    title: "Vacances au ski hors des Alpes : nos destinations originales",
    excerpt: "Pyrénées familiales, Dolomites spectaculaires, poudreuse canadienne ou japonaise : nos idées de stations hors des Alpes pour renouveler vos vacances à la neige.",
    heroImg: "/generated/blog-vacances-au-ski-hors-alpes-hero.jpg",
    heroAlt: "Station de ski enneigée avec village de montagne et pistes ensoleillées",
  },
  {
    slug: "voyage-bien-etre-spa",
    category: "Inspiration",
    date: "août 2025",
    readingTime: "8 min",
    title: "Voyage bien-être : nos plus belles destinations spa",
    excerpt: "Retraites de yoga à Bali, spas suspendus aux Maldives, hammams marocains ou ayurvéda en Inde : nos destinations pour se ressourcer corps et esprit.",
    heroImg: "/generated/blog-voyage-bien-etre-spa-hero.jpg",
    heroAlt: "Piscine à débordement d'un spa tropical face à une nature luxuriante",
  },
  {
    slug: "croisiere-premiere-fois-conseils",
    category: "Conseils",
    date: "septembre 2025",
    readingTime: "6 min",
    title: "Première croisière : nos conseils pour bien la réussir",
    excerpt: "Compagnie, cabine, mal de mer, budget et excursions : tout ce qu'il faut savoir pour bien préparer votre toute première croisière et en profiter pleinement.",
    heroImg: "/generated/blog-croisiere-premiere-fois-conseils-hero.jpg",
    heroAlt: "Grand navire de croisière voguant sur l'océan au coucher du soleil, ponts illuminés",
  },
  {
    slug: "voyage-avec-ados-idees",
    category: "Inspiration",
    date: "octobre 2025",
    readingTime: "7 min",
    title: "Voyage avec des ados : nos idées pour les emballer",
    excerpt: "Aventure, villes branchées, road trips et plages sportives : nos meilleures idées de destinations pour voyager avec des adolescents sans entendre « je m'ennuie ».",
    heroImg: "/generated/blog-voyage-avec-ados-idees-hero.jpg",
    heroAlt: "Adolescents en randonnée souriants devant un paysage de montagne spectaculaire",
  },
  {
    slug: "slow-travel-guide",
    category: "Conseils",
    date: "novembre 2025",
    readingTime: "5 min",
    title: "Le slow travel : l'art de voyager autrement",
    excerpt: "Prendre son temps, vivre au rythme local et privilégier la rencontre : découvrez la philosophie du slow travel pour des voyages plus profonds et authentiques.",
    heroImg: "/generated/blog-slow-travel-guide-hero.jpg",
    heroAlt: "Voyageur contemplant un paysage de campagne paisible depuis un train panoramique",
  },
  {
    slug: "destinations-plongee-debutant",
    category: "Conseils",
    date: "décembre 2025",
    readingTime: "8 min",
    title: "Plongée pour débutants : où commencer ?",
    excerpt: "Eaux chaudes, faibles profondeurs et fonds spectaculaires : les meilleures destinations pour faire votre baptême de plongée ou débuter le snorkeling en toute confiance.",
    heroImg: "/generated/blog-destinations-plongee-debutant-hero.jpg",
    heroAlt: "Plongeur débutant explorant un récif corallien coloré dans une eau turquoise claire",
  },
  {
    slug: "voyage-photo-plus-beaux-spots",
    category: "Inspiration",
    date: "janvier 2026",
    readingTime: "6 min",
    title: "Voyage photo : les plus beaux spots du monde",
    excerpt: "Aurores boréales, déserts, rizières et cités mythiques : notre sélection des plus beaux spots photo de la planète et nos conseils pour des clichés inoubliables.",
    heroImg: "/generated/blog-voyage-photo-plus-beaux-spots-hero.jpg",
    heroAlt: "Photographe au sommet d'une montagne capturant un lever de soleil spectaculaire",
  },
  {
    slug: "vacances-nature-deconnexion",
    category: "Inspiration",
    date: "février 2026",
    readingTime: "7 min",
    title: "Vacances nature : se déconnecter pour mieux se retrouver",
    excerpt: "Cabanes perchées, lacs sauvages et grands espaces : nos plus belles idées pour couper du quotidien et renouer avec le rythme de la nature.",
    heroImg: "/generated/blog-vacances-nature-deconnexion-hero.jpg",
    heroAlt: "Cabane en bois au bord d'un lac entouré de forêt au lever du soleil",
  },
  {
    slug: "partir-hors-saison-avantages",
    category: "Conseils",
    date: "mars 2026",
    readingTime: "5 min",
    title: "Partir hors saison : tous les avantages d'un voyage à contre-courant",
    excerpt: "Tarifs en baisse, monuments sans la foule et accueil plus chaleureux : voici pourquoi voyager hors saison change tout — et comment bien s'y prendre.",
    heroImg: "/generated/blog-partir-hors-saison-avantages-hero.jpg",
    heroAlt: "Voyageur seul devant un monument célèbre sans aucune foule autour",
  },
  {
    slug: "preparer-sa-valise-voyage",
    category: "Pratique",
    date: "avril 2026",
    readingTime: "8 min",
    title: "Préparer sa valise : la check-list pour ne rien oublier",
    excerpt: "Vêtements, papiers, trousse de secours et astuces de pro : la méthode complète pour boucler sa valise sereinement et voyager léger.",
    heroImg: "/generated/blog-preparer-sa-valise-voyage-hero.jpg",
    heroAlt: "Valise ouverte soigneusement rangée avec vêtements pliés et accessoires de voyage",
  },
  {
    slug: "eviter-le-jet-lag",
    category: "Pratique",
    date: "mai 2026",
    readingTime: "6 min",
    title: "Éviter le jet lag : nos astuces pour s'adapter au décalage horaire",
    excerpt: "Avant, pendant et après le vol : nos conseils concrets pour limiter le décalage horaire et profiter de votre destination dès l'arrivée.",
    heroImg: "/generated/blog-eviter-le-jet-lag-hero.jpg",
    heroAlt: "Vue depuis un hublot d'avion sur les nuages au coucher du soleil",
  },
  {
    slug: "choisir-assurance-voyage",
    category: "Pratique",
    date: "juin 2026",
    readingTime: "7 min",
    title: "Bien choisir son assurance voyage : le guide pratique",
    excerpt: "Annulation, frais médicaux, rapatriement, bagages : comprenez les garanties essentielles et apprenez à choisir l'assurance voyage adaptée à votre séjour.",
    heroImg: "/generated/blog-choisir-assurance-voyage-hero.jpg",
    heroAlt: "Passeport, carte du monde et documents de voyage posés sur une table",
  },
  {
    slug: "voyager-pas-cher-astuces",
    category: "Pratique",
    date: "janvier 2025",
    readingTime: "5 min",
    title: "Voyager pas cher : 15 astuces qui marchent vraiment",
    excerpt: "Quinze leviers concrets pour réduire la facture de vos voyages sans sacrifier le plaisir : vols, dates, hébergement et bons réflexes du quotidien.",
    heroImg: "/generated/blog-voyager-pas-cher-astuces-hero.jpg",
    heroAlt: "Voyageur sac au dos contemplant un paysage spectaculaire au coucher du soleil",
  },
  {
    slug: "prendre-avion-premiere-fois",
    category: "Pratique",
    date: "février 2025",
    readingTime: "8 min",
    title: "Prendre l'avion pour la première fois : le guide complet",
    excerpt: "De l'arrivée à l'aéroport à l'atterrissage, toutes les étapes expliquées pas à pas pour aborder votre premier vol en toute sérénité.",
    heroImg: "/generated/blog-prendre-avion-premiere-fois-hero.jpg",
    heroAlt: "Vue de l'aile d'un avion à travers un hublot au-dessus des nuages",
  },
  {
    slug: "formalites-visa-voyage",
    category: "Pratique",
    date: "mars 2025",
    readingTime: "6 min",
    title: "Visa et formalités : le guide pratique avant de partir",
    excerpt: "Passeport, visa, ESTA, vaccins et assurances : toutes les formalités à anticiper pour franchir les frontières sans accroc.",
    heroImg: "/generated/blog-formalites-visa-voyage-hero.jpg",
    heroAlt: "Passeport ouvert couvert de tampons de douane et de visas",
  },
  {
    slug: "voyager-avec-bebe-conseils",
    category: "Pratique",
    date: "avril 2025",
    readingTime: "7 min",
    title: "Voyager avec un bébé : nos conseils pour un séjour serein",
    excerpt: "Préparer l'avion, alléger les bagages, gérer le rythme et la santé : tout ce qu'il faut anticiper pour voyager apaisé avec votre tout-petit.",
    heroImg: "/generated/blog-voyager-avec-bebe-conseils-hero.jpg",
    heroAlt: "Parents avec un bébé dans un aéroport, prêts à embarquer",
  },
  {
    slug: "budget-voyage-bien-calculer",
    category: "Pratique",
    date: "mai 2025",
    readingTime: "5 min",
    title: "Bien calculer son budget voyage : la méthode poste par poste",
    excerpt: "Une méthode claire pour estimer chaque poste de dépense, prévoir une marge et partir sereinement, sans mauvaise surprise au retour.",
    heroImg: "/generated/blog-budget-voyage-bien-calculer-hero.jpg",
    heroAlt: "Carnet de planification de voyage, carte du monde et calculatrice sur une table",
  },
  {
    slug: "voyage-responsable-ecotourisme",
    category: "Pratique",
    date: "juin 2025",
    readingTime: "8 min",
    title: "Voyage responsable : le guide de l'écotourisme",
    excerpt: "Réduire son empreinte, soutenir l'économie locale et préserver la nature : nos conseils concrets pour voyager autrement, sans renoncer au plaisir.",
    heroImg: "/generated/blog-voyage-responsable-ecotourisme-hero.jpg",
    heroAlt: "Sentier de randonnée au cœur d'une nature verdoyante préservée",
  },
  {
    slug: "decouvrir-destination-en-train",
    category: "Inspiration",
    date: "juillet 2025",
    readingTime: "6 min",
    title: "Voyager en train : nos plus beaux trajets",
    excerpt: "Glacier Express, Transsibérien, côtes d'Écosse ou Sri Lanka : nos itinéraires ferroviaires les plus spectaculaires pour voyager autrement.",
    heroImg: "/generated/blog-decouvrir-destination-en-train-hero.jpg",
    heroAlt: "Train panoramique traversant un paysage de montagne spectaculaire",
  },
  {
    slug: "meilleures-applis-voyage",
    category: "Pratique",
    date: "août 2025",
    readingTime: "7 min",
    title: "Les meilleures applis pour voyager",
    excerpt: "Vols, navigation hors-ligne, traduction, budget et organisation : notre sélection d'applis indispensables pour préparer et vivre vos voyages sereinement.",
    heroImg: "/generated/blog-meilleures-applis-voyage-hero.jpg",
    heroAlt: "Smartphone affichant une carte de navigation lors d'un voyage",
  },
  {
    slug: "ou-partir-au-soleil-en-hiver",
    category: "Inspiration",
    date: "septembre 2025",
    readingTime: "5 min",
    title: "Où partir au soleil en hiver ?",
    excerpt: "Des Canaries aux Maldives en passant par la Thaïlande : nos destinations préférées pour troquer la grisaille hivernale contre du soleil garanti.",
    heroImg: "/generated/blog-ou-partir-au-soleil-en-hiver-hero.jpg",
    heroAlt: "Plage tropicale ensoleillée bordée de palmiers en plein hiver",
  },
  {
    slug: "ou-partir-pas-cher-en-europe",
    category: "Inspiration",
    date: "octobre 2025",
    readingTime: "8 min",
    title: "Où partir pas cher en Europe ?",
    excerpt: "Cracovie, Porto, Budapest, les Balkans ou les Pouilles : nos destinations européennes pleines de charme où votre budget va plus loin.",
    heroImg: "/generated/blog-ou-partir-pas-cher-en-europe-hero.jpg",
    heroAlt: "Vieille ville européenne pittoresque aux façades colorées",
  },
  {
    slug: "circuit-canada-rocheuses-quebec",
    category: "Circuit",
    date: "juillet 2026",
    readingTime: "6 min",
    title: "Des Rocheuses à Québec : le grand circuit du Canada",
    excerpt: "Lacs turquoise de l'Alberta, effervescence de Toronto, charme européen de Montréal et âme française de Québec : un voyage d'ouest en est à travers l'immensité canadienne.",
    heroImg: "https://images.unsplash.com/photo-1503614472-8c93d56e92ce?w=1600&h=900&fit=crop&auto=format",
    heroAlt: "Route panoramique serpentant à travers les montagnes enneigées des Rocheuses canadiennes bordées de forêts de conifères",
  },
  {
    slug: "circuit-costa-rica-volcans-jungle",
    category: "Circuit",
    date: "juillet 2026",
    readingTime: "6 min",
    title: "Costa Rica : volcans, jungle et côte Pacifique",
    excerpt: "Un volcan fumant, une forêt de nuages, des canaux peuplés de paresseux et des plages sauvages : le Costa Rica concentre en un circuit toute la richesse de l'Amérique centrale.",
    heroImg: "https://images.unsplash.com/photo-1500049242364-5f500807cdd7?w=1600&h=900&fit=crop&auto=format",
    heroAlt: "Plage sauvage de sable doré bordée d'une jungle dense et de palmiers sur la côte Pacifique du Costa Rica",
  },
  {
    slug: "circuit-maroc-marrakech-atlas-sahara",
    category: "Circuit",
    date: "juillet 2026",
    readingTime: "6 min",
    title: "Circuit Maroc : Marrakech, l'Atlas et le Sahara",
    excerpt: "Souks colorés, cols vertigineux du Haut Atlas, kasbahs de terre et nuit sous les étoiles dans le désert : notre circuit pour découvrir le meilleur du Maroc.",
    heroImg: "https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=1600&h=900&fit=crop&auto=format",
    heroAlt: "Dunes dorées du Sahara marocain ondulant à perte de vue sous la lumière chaude du coucher du soleil",
  },
  {
    slug: "croisiere-mediterranee-rome-barcelone",
    category: "Croisière",
    date: "juillet 2026",
    readingTime: "6 min",
    title: "Croisière en Méditerranée : Rome, Barcelone et la Côte d'Azur",
    excerpt: "Des trésors de Rome à la Sagrada Família de Barcelone, en passant par la Toscane et la Côte d'Azur : notre itinéraire pour une croisière inoubliable en Méditerranée.",
    heroImg: "https://images.unsplash.com/photo-1515859005217-8a1f08870f59?w=1600&h=900&fit=crop&auto=format",
    heroAlt: "Grand navire de croisière naviguant sur une mer Méditerranée calme baignée par la lumière dorée du coucher du soleil",
  },
  {
    slug: "croisiere-fjords-norvegiens",
    category: "Croisière",
    date: "juillet 2026",
    readingTime: "6 min",
    title: "Fjords norvégiens & aurores boréales : notre croisière de rêve",
    excerpt: "Parois vertigineuses, cascades, soleil de minuit l'été et aurores boréales l'hiver : embarquez pour la Norvège, l'une des plus belles croisières du monde.",
    heroImg: "https://images.unsplash.com/photo-1520769945061-0a448c463865?w=1600&h=900&fit=crop&auto=format",
    heroAlt: "Fjord norvégien spectaculaire avec un navire de croisière au pied de montagnes escarpées plongeant dans une eau sombre",
  },
  {
    slug: "croisiere-caraibes-antilles",
    category: "Croisière",
    date: "juillet 2026",
    readingTime: "6 min",
    title: "Îles des Caraïbes & Antilles : notre croisière au paradis",
    excerpt: "Plages de sable blanc, eaux turquoise, fonds marins et îles françaises comme anglophones : embarquez pour une croisière ensoleillée au cœur des Antilles.",
    heroImg: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1600&h=900&fit=crop&auto=format",
    heroAlt: "Plage de sable blanc bordée de cocotiers penchés au-dessus d'une eau turquoise et transparente dans les Caraïbes",
  },
  {
    slug: "croisiere-fluviale-europe",
    category: "Croisière",
    date: "juillet 2026",
    readingTime: "6 min",
    title: "Croisière fluviale en Europe : Douro, Rhin & Danube",
    excerpt: "Petits bateaux, escales au cœur des villes et formule tout compris : la croisière fluviale réinvente le voyage. Cap sur le Douro, le Rhin et le Danube.",
    heroImg: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1600&h=900&fit=crop&auto=format",
    heroAlt: "Bateau de croisière fluviale glissant sur un fleuve européen bordé de vignobles en terrasses",
  },
  {
    slug: "glamping-cabane-canada",
    category: "Glamping",
    date: "juillet 2026",
    readingTime: "6 min",
    title: "Glamping au Canada : une cabane en rondins au bord d'un lac",
    excerpt: "Le confort d'un lodge, la magie de la nature boréale : imaginez une cabane en rondins face à un lac canadien, entre jacuzzi, canoë et aurores boréales.",
    heroImg: "https://images.unsplash.com/photo-1509233725247-49e657c54213?w=1600&h=900&fit=crop&auto=format",
    heroAlt: "Cabane en rondins au bord d'un lac paisible entouré de forêt au Canada",
  },
  {
    slug: "glamping-eco-lodge-costa-rica",
    category: "Glamping",
    date: "juillet 2026",
    readingTime: "6 min",
    title: "Éco-lodge en forêt tropicale au Costa Rica",
    excerpt: "Un bungalow perché dans la canopée, le réveil au chant des toucans et la promesse d'un tourisme responsable : découvrez le glamping éco-lodge au cœur de la jungle costaricienne.",
    heroImg: "https://images.unsplash.com/photo-1500049242364-5f500807cdd7?w=1600&h=900&fit=crop&auto=format",
    heroAlt: "Éco-lodge en bois niché dans la canopée d'une forêt tropicale luxuriante du Costa Rica",
  },
  {
    slug: "glamping-ryokan-japon",
    category: "Glamping",
    date: "juillet 2026",
    readingTime: "6 min",
    title: "Ryokan traditionnel avec bains onsen au Japon",
    excerpt: "Dormir sur un futon posé à même le tatami, se délasser dans une source thermale face aux montagnes et savourer un repas kaiseki : le ryokan est l'expérience insolite la plus authentique du Japon.",
    heroImg: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1600&h=900&fit=crop&auto=format",
    heroAlt: "Ryokan japonais traditionnel avec un bain onsen extérieur en pierre entouré de nature",
  },
];
